### ISSUE TITLE
gr-qwt5: needs python-qwt5-qt4 on Ubuntu 16.04

### ISSUE THREAD

**Issue by mattypiper** [gnuradio/gr-recipes#106]
Clean setup of pybombs on Ubuntu 16.04, trying to run an example from [gr-psk-burst](https://github.com/osh/gr-psk-burst), I get an import error:

```
Generating: '/home/user/gnuradio-pybombs/src/gr-psk-burst/psk_burst_tx.py'

Executing: /usr/bin/python2 -u /home/user/gnuradio-pybombs/src/gr-psk-burst/psk_burst_tx.py

/usr/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/home/user/gnuradio-pybombs/src/gr-psk-burst/psk_burst_tx.py", line 33, in <module>
    import pyqt
  File "/home/user/gnuradio-pybombs/lib/python2.7/dist-packages/pyqt/__init__.py", line 52, in <module>
    from plotter_base import *;
  File "/home/user/gnuradio-pybombs/lib/python2.7/dist-packages/pyqt/plotter_base.py", line 27, in <module>
    import PyQt4.Qwt5 as Qwt
ImportError: No module named Qwt5

>>> Done (return code 1)
```

The issue was resolved after I ran `sudo apt install python-qwt5-qt4`. Does this need added as a requirement?

**Comment by mbr0wn** [comment]
I guess so! -> b0699f85312c7c697b4409cdccc63144419634d1
