### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by keanesf** [gnuradio/gr-recipes#127]
`pybombs recipes add gr-recipes https://github.com/gnuradio/gr-recipes.git
PyBOMBS - INFO - PyBOMBS Version 2.3.2
PyBOMBS.Packager.apt - INFO - Install python-apt to speed up apt processing.
Traceback (most recent call last):
  File "/usr/local/bin/pybombs", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pybombs/main.py", line 32, in main
    return dispatch() or 0
  File "/usr/local/lib/python2.7/dist-packages/pybombs/commands/base.py", line 194, in dispatch
    return get_cmd_dict(cmd_list)[args.command](cmd=args.command, args=args).run()
  File "/usr/local/lib/python2.7/dist-packages/pybombs/commands/base.py", line 120, in run
    return self.subcommands[self.args.sub_command]['run'](self)()
  File "/usr/local/lib/python2.7/dist-packages/pybombs/commands/recipes.py", line 172, in run_add
    if not self.add_recipe_dir(alias, uri):
  File "/usr/local/lib/python2.7/dist-packages/pybombs/commands/recipes.py", line 347, in add_recipe_dir
    Fetcher().fetch_url(uri, recipe_cache_top_level, alias, {}) # No args
  File "/usr/local/lib/python2.7/dist-packages/pybombs/fetcher.py", line 72, in fetch_url
    fetcher.assert_requirements()
  File "/usr/local/lib/python2.7/dist-packages/pybombs/requirer.py", line 80, in assert_requirements
    require_hostsys_dependencies(requirements)
  File "/usr/local/lib/python2.7/dist-packages/pybombs/requirer.py", line 50, in require_hostsys_dependencies
    install_type="binary", # Requirers may not request source packages
  File "/usr/local/lib/python2.7/dist-packages/pybombs/install_manager.py", line 112, in install
    lambda pkg: _cached_check_if_pkg_goes_into_tree(pkg, _check_if_pkg_goes_into_tree)
  File "/usr/local/lib/python2.7/dist-packages/pybombs/dep_manager.py", line 53, in make_dep_tree
    pkg_set = set([pkg for pkg in pkg_list if filter_callback(pkg)])
  File "/usr/local/lib/python2.7/dist-packages/pybombs/install_manager.py", line 112, in <lambda>
    lambda pkg: _cached_check_if_pkg_goes_into_tree(pkg, _check_if_pkg_goes_into_tree)
  File "/usr/local/lib/python2.7/dist-packages/pybombs/install_manager.py", line 97, in _cached_check_if_pkg_goes_into_tree
    ret_val = check_callback(pkg)
  File "/usr/local/lib/python2.7/dist-packages/pybombs/install_manager.py", line 63, in _check_if_pkg_goes_into_tree
    if not self.pm.exists(pkg):
  File "/usr/local/lib/python2.7/dist-packages/pybombs/package_manager.py", line 128, in exists
    if self.check_package_flag(name, 'forceinstalled'):
  File "/usr/local/lib/python2.7/dist-packages/pybombs/package_manager.py", line 89, in check_package_flag
    recipe.get_recipe(pkgname).category
  File "/usr/local/lib/python2.7/dist-packages/pybombs/recipe.py", line 383, in get_recipe
    r = Recipe(recipe_manager.recipe_manager.get_recipe_filename(pkgname))
  File "/usr/local/lib/python2.7/dist-packages/pybombs/recipe.py", line 219, in __init__
    self._data = self._load_recipe_from_file(filename)
  File "/usr/local/lib/python2.7/dist-packages/pybombs/recipe.py", line 256, in _load_recipe_from_file
    data = PBConfigFile(filename).get()
  File "/usr/local/lib/python2.7/dist-packages/pybombs/config_file.py", line 84, in __init__
    assert isinstance(self.data, dict)
AssertionError`

**Comment by keanesf** [comment]
https://github.com/gnuradio/pybombs/issues/512
